package enums;

public enum GameVariant {
    ELFENLAND_CLASSIC,
    ELFENLAND_LONG,
    ELFENLAND_DESTINATION,
    ELFENGOLD_CLASSIC,
    ELFENGOLD_DESTINATION,
    ELFENGOLD_RANDOM_GOLD,
    ELFENGOLD_WITCH
}
